Create mvp-template-12-multiomics-drugapprovals-faers.json
TranslatorSRI/CQS pull request #60
Opened 2024-11-01 18:12 UTC by mbrush

Adding new template for faers-based treats predictions from edges in the multiomics drug-approvals kp (to replace the current aeolus-baed template).

2024-11-04 19:12 UTC, karafecho requested changes
This looks good, except for the `results_limit `field, which I think should have a value of, e.g., 50, not 5.6.

2024-11-04 20:24 UTC, mbrush commented
@jdr0887 can you comment on why the results limit is 5.6?   It looks like this is set in many of the mvp1 templates (including the ctkp one, and the aeolus one on which I based this multiomics-drugapprovals template). I assume you added this limit in these templates.  Can you make sure this limit is set appropriately **across ALL MVP1 templates**?

2024-11-04 21:00 UTC, jdr0887 commented
results_limit is now a proportion of 500 total results. All templates have been updated accordingly.

2024-11-04 21:29 UTC, jdr0887 approved these changes

2024-11-05 14:26 UTC, jdr0887 approved these changes

2024-11-05 14:27 UTC, merged